package com.emos.trans.pojo;

// Generated 2014-6-24 16:56:42 by Hibernate Tools 3.4.0.CR1

/**
 * HomeTemp generated by hbm2java
 */
public class HomeTemp implements java.io.Serializable {

	private String homeUuid;
	private Long sessionId;

	public HomeTemp() {
	}

	public HomeTemp(String homeUuid) {
		this.homeUuid = homeUuid;
	}

	public HomeTemp(String homeUuid, Long sessionId) {
		this.homeUuid = homeUuid;
		this.sessionId = sessionId;
	}

	public String getHomeUuid() {
		return this.homeUuid;
	}

	public void setHomeUuid(String homeUuid) {
		this.homeUuid = homeUuid;
	}

	public Long getSessionId() {
		return this.sessionId;
	}

	public void setSessionId(Long sessionId) {
		this.sessionId = sessionId;
	}

}
