package com.emos.trans.pojo;

// Generated 2014-6-24 16:56:42 by Hibernate Tools 3.4.0.CR1

/**
 * UserTemp generated by hbm2java
 */
public class UserTemp implements java.io.Serializable {

	private String userName;
	private Long sessionId;
	private String boundUuid;

	public UserTemp() {
	}

	public UserTemp(String userName) {
		this.userName = userName;
	}

	public UserTemp(String userName, Long sessionId, String boundUuid) {
		this.userName = userName;
		this.sessionId = sessionId;
		this.boundUuid = boundUuid;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public Long getSessionId() {
		return this.sessionId;
	}

	public void setSessionId(Long sessionId) {
		this.sessionId = sessionId;
	}

	public String getBoundUuid() {
		return this.boundUuid;
	}

	public void setBoundUuid(String boundUuid) {
		this.boundUuid = boundUuid;
	}

}
